### ISSUE TITLE
After installing I've tried to rebuild the admin but got an error

### ISSUE THREAD

**Issue by jstam89** [ExFabrica/strapi-plugin-awesome-seo#1]
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
    at /opt/api_groenerewoning/node_modules/webpack/lib/Compilation.js:2011:28
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /opt/api_groenerewoning/node_modules/neo-async/async.js:6883:13
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
  Parsed request is a module
  using description file: /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/package.json (relative path: ./admin/src/containers/Settings/expert)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules
        /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules/@strapi/design-system doesn't exist
      /opt/api_groenerewoning/node_modules/@exfabrica/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules
        existing directory /opt/api_groenerewoning/node_modules/@strapi/design-system
          using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
      /opt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules
        /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
    at /opt/api_groenerewoning/node_modules/webpack/lib/Compilation.js:2011:28
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /opt/api_groenerewoning/node_modules/neo-async/async.js:6883:13
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
  Parsed request is a module
  using description file: /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/package.json (relative path: ./admin/src/containers/Settings/expert)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules
        /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules/@strapi/design-system doesn't exist
      /opt/api_groenerewoning/node_modules/@exfabrica/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules
        existing directory /opt/api_groenerewoning/node_modules/@strapi/design-system
          using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
      /opt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules
        /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist
```

**Comment by jstam89** [comment]
This is my package.json anything wrong with it?

```
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
    at /opt/api_groenerewoning/node_modules/webpack/lib/Compilation.js:2011:28
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /opt/api_groenerewoning/node_modules/neo-async/async.js:6883:13
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
  Parsed request is a module
  using description file: /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/package.json (relative path: ./admin/src/containers/Settings/expert)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules
        /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules/@strapi/design-system doesn't exist
      /opt/api_groenerewoning/node_modules/@exfabrica/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules
        existing directory /opt/api_groenerewoning/node_modules/@strapi/design-system
          using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
      /opt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules
        /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
    at /opt/api_groenerewoning/node_modules/webpack/lib/Compilation.js:2011:28
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /opt/api_groenerewoning/node_modules/neo-async/async.js:6883:13
    at /opt/api_groenerewoning/node_modules/webpack/lib/NormalModuleFactory.js:955:45
    at finishWithoutResolve (/opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /opt/api_groenerewoning/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/opt/api_groenerewoning/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '@strapi/design-system/Text' in '/opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert'
  Parsed request is a module
  using description file: /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/package.json (relative path: ./admin/src/containers/Settings/expert)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/expert/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/Settings/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/containers/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/src/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/admin/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules
        /opt/api_groenerewoning/node_modules/@exfabrica/strapi-plugin-awesome-seo/node_modules/@strapi/design-system doesn't exist
      /opt/api_groenerewoning/node_modules/@exfabrica/node_modules doesn't exist or is not a directory
      /opt/api_groenerewoning/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules
        existing directory /opt/api_groenerewoning/node_modules/@strapi/design-system
          using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: .)
            using description file: /opt/api_groenerewoning/node_modules/@strapi/design-system/package.json (relative path: ./Text)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.jsx doesn't exist
              .react.js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text.react.js doesn't exist
              as directory
                /opt/api_groenerewoning/node_modules/@strapi/design-system/Text doesn't exist
      /opt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules
        /opt/api_groenerewoning/node_modules/@strapi/admin/node_modules/@strapi/design-system doesn't exist
```

**Comment by jstam89** [comment]
Anything wrong with my package.json maybe?

```
{
  "name": "api-groenerewoning",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-i18n": "4.1.8",
    "@strapi/plugin-seo": "^1.7.2",
    "@strapi/plugin-users-permissions": "4.1.8",
    "@strapi/strapi": "4.1.8",
    "better-sqlite3": "^7.5.0",
    "strapi-plugin-measurement-protocol": "^1.0.1",
    "strapi-plugin-transformer": "^2.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "fb2cd738-3ea1-480b-a86a-7d855bf24d79"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by Munei89** [comment]
I am also getting the above error and there is no work around it.

**Comment by ghost** [comment]
Hi guys, 
thank's for your feedback.We work on it. Issue is due of strapi change with thes lasts updates. The fix will done soon with the next release of your plugins.

**Comment by jclaveau** [comment]
Same as here: https://github.com/ExFabrica/strapi-plugin-awesome-seo/issues/3

This works if you don't want to wait for the release.
```
yarn add git+https://github.com/ExFabrica/strapi-plugin-awesome-seo.git
yarn build
```

**Comment by mcnaveen** [comment]
Is this already fixed and released? I'm still getting the error.
